### ISSUE TITLE
existing forms are no longer recognized after updating

### ISSUE THREAD

**Issue by hillschmidt** [cmb69/advancedform_xh#74]
tried the update to version 2.0 two times but had twice to re-install the old version: my existing own created forms are no longer recognized - pages, using them, are shown with error Form <form_name> does not exist.
So: not usable for me.
Using CMSimple_XH 1.7.4  Released: 2020-10-26
Using still Advancedform_xh Version: 1.2

**Comment by cmb69** [comment]
You likely need to replace the contents of the data/ folder of the new installation with your old data/ folder. Afterwards, go to the plugin administration; your old forms should have been imported.

Note that the plugin looks for data/forms.json, and if this file doesn't exist, it looks for data/forms.dat, and if that exists, it is converted to data/forms.json. On the next request, the converted data/forms.json should be read.

**Comment by hillschmidt** [comment]
Thanks - it works! What will happen, if the update package does not contain this json file? In my thinking, the existing .dat file will be read - .json is created - conversion done. No manual change needed. Or do I misinterpret?

**Comment by cmb69** [comment]
Yes, that would work; however, Advancedform_XH-2.0.zip isn't meant as *update* package (i.e. just upload over the old plugin), due to too many mostly internal changes for that to be practical. In other words, if I omitted the data/ folder from the ZIP, too many old files in other folders would not be deleted (not a big deal, but still confusing), and there might be other issues.

Anyhow, I've changed the release announcement to link to this issue; that may help others to figure out how to do the update. Thanks for reporting! :)
